ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }

    application {
        modules = [ com.mathstack.ApplicationKt.module ]
    }
}

database {
    # Valores por defecto para LOCAL
    url = "jdbc:postgresql://localhost:5432/postgres"
    url = ${?DB_URL}
    driver = "org.postgresql.Driver"
    driver = ${?DB_DRIVER}
    user = "postgres"
    user = ${?DB_USER}
    password = "1234"  # <--- Cambia esto por tu contraseña de PostgreSQL local
    password = ${?DB_PASSWORD}
}

jwt {
    # Valores por defecto para LOCAL
    issuer = "http://localhost:8080/"
    issuer = ${?JWT_ISSUER}
    audience = "mathstack-audience"
    audience = ${?JWT_AUDIENCE}
    realm = "MathStack Local"
    realm = ${?JWT_REALM}
    secret = "super-secret-local-key-mathstack-12345"
    secret = ${?JWT_SECRET}
}