ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }

    application {
        modules = [ com.mathstack.ApplicationKt.module ]
    }
}

database {
    url = ${?DB_URL}
    driver = ${?DB_DRIVER}
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
}

jwt {
    issuer = ${?JWT_ISSUER}
    audience = ${?JWT_AUDIENCE}
    realm = ${?JWT_REALM}
    secret = ${?JWT_SECRET}
}