ktor {
    deployment {
        port = ${?PORT}
    }

    application {
        modules = [ com.mathstack.ApplicationKt.module ]
    }
}

database {
    url = ${?DB_URL}
    driver = ${?DB_DRIVER}
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
}

jwt {
    issuer = "mathstack"
    audience = "mathstack-api"
    realm = "mathstack"
    secret = ${?JWT_SECRET}
}